modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL="https://modrinth.com/mod/keypreset"
issueTrackerURL="https://github.com/Memory-Yzf/KeyPreset/issues"
authors = "${mod_authors}"
logoFile = "logo.png"
description = '''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[modproperties.modmenu]
badges=["client"]
sources="https://github.com/Memory-Yzf/KeyPreset"
links=["mod_menu.modrinth=https://modrinth.com/mod/keypreset", "mod_menu.curseforge=https://www.curseforge.com/minecraft/mc-mods/keypreset"]

[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "CLIENT"